### PR TITLE
fixed the divide by zero error.

### PR DESCRIPTION
**Pull request by thejmdw**
Description of PR that completes issue here...

## Changes

- bangazonapi/views/paymenttype.py

## Requests / Responses

If this PR contains code that defines a new request/response, or changes an existing one, please put the JSON representations here.

**Request**

POST `/products` Creates a new product

```json
{
    "title": "Kite",
    "product_type_id": 1,
    "description": "Red. It flies high.",
    "quantity": 5
}
```

**Response**

HTTP/1.1 201 OK

```json
{
    "id": 54,
    "title": "Kite",
    "product_type_id": 1,
    "description": "Red. It flies high.",
    "quantity": 5
}
```

## Testing

Description of how to test code...

- [ ] Run migrations
- [ ] Run test suite
- [ ] Seed database

- [ ] Open Postman
- [ ] Collections
- [ ] Get all payment types

- [ ] Returns payment type(s) for only the current user

## Related Issues

- Bugs #18

### CODE REVIEW

**Review by gwynnemeeks — CHANGES_REQUESTED** [review]
Remove commented out code on line 86

**Comment by thejmdw** [comment]
It isn't getting the appropriate customer_id anyway, so I'm re working the code. Will remove that line once I get this working.

**Review by gwynnemeeks — APPROVED** [review]
approved

**Comment by thejmdw** [comment]
Thanks Gwynne!

**Pull request merged**
